// MIT License
// Copyright (c) 2023 Lauri Lorenzo Fiestas
// https://github.com/PrinssiFiestas/libGPC/blob/main/LICENSE.md

#include <gpc/gpatomic.h>

// See ../tests/bench_atomic.c for mutex pool vs atomics discussion.

#if defined(GP_USE_INTERLOCKED_INTRINSICS) && defined(GP_TARGET_ARCH_X86)

GPMutex gp_g_atomic_mutex_pool[256] =
{
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
};

#elif defined(GP_USE_LOCKS_FOR_ATOMICS)

#include <string.h> // memcpy()

static GPMutex gp_s_atomic_mutex_pool[256] =
{
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
    GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT, GP_MUTEX_INIT,
};
#define GP_GET_ATOMIC_MUTEX(PTR) \
( \
    &gp_s_atomic_mutex_pool[((uintptr_t)(PTR)) & (countof(gp_s_atomic_mutex_pool) - 1)] \
)

// Nasty and lazy macro templating here, readability and debuggability takes a hit, sorry!
// Note: memcpy() used instead of direct access, sizeof selection requires this
// to get around strict aliasing for C99 generic macro functions.

#define GP_ATOMIC_STORE_TEMPLATE(POSTFIX, GPT, T) \
void gp_atomic_store_##POSTFIX (GPT* a, T c) \
{ \
    GPMutex* mutex = GP_GET_ATOMIC_MUTEX(a); \
    gp_mutex_lock(mutex); \
    memcpy(a, &c, sizeof(c)); \
    gp_mutex_unlock(mutex); \
}
GP_ATOMIC_STORE_TEMPLATE(i8 , GPAtomicInt8  , int8_t  )
GP_ATOMIC_STORE_TEMPLATE(u8 , GPAtomicUInt8 , uint8_t )
GP_ATOMIC_STORE_TEMPLATE(i16, GPAtomicInt16 , int16_t )
GP_ATOMIC_STORE_TEMPLATE(u16, GPAtomicUInt16, uint16_t)
GP_ATOMIC_STORE_TEMPLATE(i32, GPAtomicInt32 , int32_t )
GP_ATOMIC_STORE_TEMPLATE(u32, GPAtomicUInt32, uint32_t)
GP_ATOMIC_STORE_TEMPLATE(i64, GPAtomicInt64 , int64_t )
GP_ATOMIC_STORE_TEMPLATE(u64, GPAtomicUInt64, uint64_t)

#define GP_ATOMIC_LOAD_TEMPLATE(POSTFIX, GPT, T) \
T gp_atomic_load_##POSTFIX (const GPT* a) \
{ \
    GPMutex* mutex = GP_GET_ATOMIC_MUTEX(a); \
    gp_mutex_lock(mutex); \
    T c; \
    memcpy(&c, a, sizeof(c)); \
    gp_mutex_unlock(mutex); \
    return c; \
}
GP_ATOMIC_LOAD_TEMPLATE(i8 , GPAtomicInt8  , int8_t  )
GP_ATOMIC_LOAD_TEMPLATE(u8 , GPAtomicUInt8 , uint8_t )
GP_ATOMIC_LOAD_TEMPLATE(i16, GPAtomicInt16 , int16_t )
GP_ATOMIC_LOAD_TEMPLATE(u16, GPAtomicUInt16, uint16_t)
GP_ATOMIC_LOAD_TEMPLATE(i32, GPAtomicInt32 , int32_t )
GP_ATOMIC_LOAD_TEMPLATE(u32, GPAtomicUInt32, uint32_t)
GP_ATOMIC_LOAD_TEMPLATE(i64, GPAtomicInt64 , int64_t )
GP_ATOMIC_LOAD_TEMPLATE(u64, GPAtomicUInt64, uint64_t)

#define GP_ATOMIC_OP_TEMPLATE(NAME, POSTFIX, GPT, T, OP) \
T gp_atomic_##NAME##_##POSTFIX (GPT* a, T c) \
{ \
    GPMutex* mutex = GP_GET_ATOMIC_MUTEX(a); \
    gp_mutex_lock(mutex); \
    T old, new; \
    memcpy(&old, a, sizeof old); \
    new = old; \
    new OP c; \
    memcpy(a, &new, sizeof new); \
    gp_mutex_unlock(mutex); \
    return old; \
}

GP_ATOMIC_OP_TEMPLATE(exchange, i8 , GPAtomicInt8  , int8_t  , =)
GP_ATOMIC_OP_TEMPLATE(exchange, u8 , GPAtomicUInt8 , uint8_t , =)
GP_ATOMIC_OP_TEMPLATE(exchange, i16, GPAtomicInt16 , int16_t , =)
GP_ATOMIC_OP_TEMPLATE(exchange, u16, GPAtomicUInt16, uint16_t, =)
GP_ATOMIC_OP_TEMPLATE(exchange, i32, GPAtomicInt32 , int32_t , =)
GP_ATOMIC_OP_TEMPLATE(exchange, u32, GPAtomicUInt32, uint32_t, =)
GP_ATOMIC_OP_TEMPLATE(exchange, i64, GPAtomicInt64 , int64_t , =)
GP_ATOMIC_OP_TEMPLATE(exchange, u64, GPAtomicUInt64, uint64_t, =)

GP_ATOMIC_OP_TEMPLATE(fetch_add, i8 , GPAtomicInt8  , int8_t  , +=)
GP_ATOMIC_OP_TEMPLATE(fetch_add, u8 , GPAtomicUInt8 , uint8_t , +=)
GP_ATOMIC_OP_TEMPLATE(fetch_add, i16, GPAtomicInt16 , int16_t , +=)
GP_ATOMIC_OP_TEMPLATE(fetch_add, u16, GPAtomicUInt16, uint16_t, +=)
GP_ATOMIC_OP_TEMPLATE(fetch_add, i32, GPAtomicInt32 , int32_t , +=)
GP_ATOMIC_OP_TEMPLATE(fetch_add, u32, GPAtomicUInt32, uint32_t, +=)
GP_ATOMIC_OP_TEMPLATE(fetch_add, i64, GPAtomicInt64 , int64_t , +=)
GP_ATOMIC_OP_TEMPLATE(fetch_add, u64, GPAtomicUInt64, uint64_t, +=)

GP_ATOMIC_OP_TEMPLATE(fetch_sub, i8 , GPAtomicInt8  , int8_t  , -=)
GP_ATOMIC_OP_TEMPLATE(fetch_sub, u8 , GPAtomicUInt8 , uint8_t , -=)
GP_ATOMIC_OP_TEMPLATE(fetch_sub, i16, GPAtomicInt16 , int16_t , -=)
GP_ATOMIC_OP_TEMPLATE(fetch_sub, u16, GPAtomicUInt16, uint16_t, -=)
GP_ATOMIC_OP_TEMPLATE(fetch_sub, i32, GPAtomicInt32 , int32_t , -=)
GP_ATOMIC_OP_TEMPLATE(fetch_sub, u32, GPAtomicUInt32, uint32_t, -=)
GP_ATOMIC_OP_TEMPLATE(fetch_sub, i64, GPAtomicInt64 , int64_t , -=)
GP_ATOMIC_OP_TEMPLATE(fetch_sub, u64, GPAtomicUInt64, uint64_t, -=)

GP_ATOMIC_OP_TEMPLATE(fetch_or, i8 , GPAtomicInt8  , int8_t  , |=)
GP_ATOMIC_OP_TEMPLATE(fetch_or, u8 , GPAtomicUInt8 , uint8_t , |=)
GP_ATOMIC_OP_TEMPLATE(fetch_or, i16, GPAtomicInt16 , int16_t , |=)
GP_ATOMIC_OP_TEMPLATE(fetch_or, u16, GPAtomicUInt16, uint16_t, |=)
GP_ATOMIC_OP_TEMPLATE(fetch_or, i32, GPAtomicInt32 , int32_t , |=)
GP_ATOMIC_OP_TEMPLATE(fetch_or, u32, GPAtomicUInt32, uint32_t, |=)
GP_ATOMIC_OP_TEMPLATE(fetch_or, i64, GPAtomicInt64 , int64_t , |=)
GP_ATOMIC_OP_TEMPLATE(fetch_or, u64, GPAtomicUInt64, uint64_t, |=)

GP_ATOMIC_OP_TEMPLATE(fetch_xor, i8 , GPAtomicInt8  , int8_t  , ^=)
GP_ATOMIC_OP_TEMPLATE(fetch_xor, u8 , GPAtomicUInt8 , uint8_t , ^=)
GP_ATOMIC_OP_TEMPLATE(fetch_xor, i16, GPAtomicInt16 , int16_t , ^=)
GP_ATOMIC_OP_TEMPLATE(fetch_xor, u16, GPAtomicUInt16, uint16_t, ^=)
GP_ATOMIC_OP_TEMPLATE(fetch_xor, i32, GPAtomicInt32 , int32_t , ^=)
GP_ATOMIC_OP_TEMPLATE(fetch_xor, u32, GPAtomicUInt32, uint32_t, ^=)
GP_ATOMIC_OP_TEMPLATE(fetch_xor, i64, GPAtomicInt64 , int64_t , ^=)
GP_ATOMIC_OP_TEMPLATE(fetch_xor, u64, GPAtomicUInt64, uint64_t, ^=)

GP_ATOMIC_OP_TEMPLATE(fetch_and, i8 , GPAtomicInt8  , int8_t  , &=)
GP_ATOMIC_OP_TEMPLATE(fetch_and, u8 , GPAtomicUInt8 , uint8_t , &=)
GP_ATOMIC_OP_TEMPLATE(fetch_and, i16, GPAtomicInt16 , int16_t , &=)
GP_ATOMIC_OP_TEMPLATE(fetch_and, u16, GPAtomicUInt16, uint16_t, &=)
GP_ATOMIC_OP_TEMPLATE(fetch_and, i32, GPAtomicInt32 , int32_t , &=)
GP_ATOMIC_OP_TEMPLATE(fetch_and, u32, GPAtomicUInt32, uint32_t, &=)
GP_ATOMIC_OP_TEMPLATE(fetch_and, i64, GPAtomicInt64 , int64_t , &=)
GP_ATOMIC_OP_TEMPLATE(fetch_and, u64, GPAtomicUInt64, uint64_t, &=)

#define GP_ATOMIC_COMPARE_EXCHANGE_TEMPLATE(WEAK_OR_STRONG, POSTFIX, GPT, T) \
bool gp_atomic_compare_exchange_##WEAK_OR_STRONG##_##POSTFIX (GPT* a, T* b, T c) \
{ \
    GPMutex* mutex = GP_GET_ATOMIC_MUTEX(a); \
    gp_mutex_lock(mutex); \
    bool is_expected = memcmp(a, b, sizeof c) == 0; \
    if (is_expected) \
        memcpy(a, c, sizeof c); } \
    else \
        memcpy(b, a, sizeof c); } \
    gp_mutex_unlock(mutex); \
    return is_expected; \
}

GP_ATOMIC_COMPARE_EXCHANGE_TEMPLATE(strong, i8 , GPAtomicInt8  , int8_t  )
GP_ATOMIC_COMPARE_EXCHANGE_TEMPLATE(strong, u8 , GPAtomicUInt8 , uint8_t )
GP_ATOMIC_COMPARE_EXCHANGE_TEMPLATE(strong, i16, GPAtomicInt16 , int16_t )
GP_ATOMIC_COMPARE_EXCHANGE_TEMPLATE(strong, u16, GPAtomicUInt16, uint16_t)
GP_ATOMIC_COMPARE_EXCHANGE_TEMPLATE(strong, i32, GPAtomicInt32 , int32_t )
GP_ATOMIC_COMPARE_EXCHANGE_TEMPLATE(strong, u32, GPAtomicUInt32, uint32_t)
GP_ATOMIC_COMPARE_EXCHANGE_TEMPLATE(strong, i64, GPAtomicInt64 , int64_t )
GP_ATOMIC_COMPARE_EXCHANGE_TEMPLATE(strong, u64, GPAtomicUInt64, uint64_t)

GP_ATOMIC_COMPARE_EXCHANGE_TEMPLATE(weak, i8 , GPAtomicInt8  , int8_t  )
GP_ATOMIC_COMPARE_EXCHANGE_TEMPLATE(weak, u8 , GPAtomicUInt8 , uint8_t )
GP_ATOMIC_COMPARE_EXCHANGE_TEMPLATE(weak, i16, GPAtomicInt16 , int16_t )
GP_ATOMIC_COMPARE_EXCHANGE_TEMPLATE(weak, u16, GPAtomicUInt16, uint16_t)
GP_ATOMIC_COMPARE_EXCHANGE_TEMPLATE(weak, i32, GPAtomicInt32 , int32_t )
GP_ATOMIC_COMPARE_EXCHANGE_TEMPLATE(weak, u32, GPAtomicUInt32, uint32_t)
GP_ATOMIC_COMPARE_EXCHANGE_TEMPLATE(weak, i64, GPAtomicInt64 , int64_t )
GP_ATOMIC_COMPARE_EXCHANGE_TEMPLATE(weak, u64, GPAtomicUInt64, uint64_t)

// Having this in a dedicated translation unit should be enough for implicit
// compiler memory barrier. The attributes are redundant since this is only
// ever used for obscure strict C99 compilers, but we'll keep them just in case.
GP_GNU_ATTRIB(noinline) GP_OPTIMIZE_NONE
void gp_atomic_signal_fence_noinline(void)
{
    (void)0;
}

#endif
